version: "3.3"

services:
  app:
    build: .
    image: nodeapp
    ports: 
      - 80:3000
    networks:
      - nodemernapp
    environment:
      - MONGO_URI=mongodb://mongo_db/nodeapp 
    depends_on: 
      - db

  db: 
    image: mongo:latest
    volumes: 
      - mongo-db:/data/db
    networks:
      nodemernapp:
        aliases:
          - mongo_db

networks:
  nodemernapp:
    driver: bridge 

volumes: 
  mongo-db: 